### ISSUE TITLE
There is a problem.

### ISSUE THREAD

**Issue by Rr7716** [coleifer/walrus#184]
I'm encountering a small probelm with the .pending method of a consumer group stream.

`receive_cg.receive_stream.pending()`

Raises

`return self.database.xpending_range(self.key, self.group, min=start,
TypeError: xpending_range() got an unexpected keyword argument 'idle'`

By looking into your code i tracked this to the following lines:

[walrus/containers.py:1286]

`return self.database.xpending_range(self.key, self.group, min=start,
                                            max=stop, count=count,
                                            consumername=consumer, idle=idle)`

It also failed though I change my code:

`receive_cg.receive_stream.pending(idle=1000)`

I don't know what's wrong with it. It's so weird.

Can you help me?

**Comment by coleifer** [comment]
What version of redis-py do you have installed?

**Comment by coleifer** [comment]
Looks like redis-py added this in commit 9c60670deea5c593e20204bbd5f172ccfcd1d9db (https://github.com/redis/redis-py/pull/1523). This was added in 4.0, so I suggest updating your redis-py to 4.0 at least.

**Comment by Rr7716** [comment]
Thank you so much!!!
I solve it after updating redis to 4.0.
